$src       = Join-Path $PSScriptRoot 'FFmpeg_Converter_run_win_v14.ps1'
$scriptPs1 = Join-Path $PSScriptRoot 'FFmpeg_Converter_script.ps1'
$out       = Join-Path $PSScriptRoot '_VideoConverter_v14.exe'
$ps2exePs  = Join-Path $PSScriptRoot '..\tools\ps2exe.ps1'
$ps2exeSha = 'FAEA495151AF69D2AE78783D0071186F98DC568D7B7478F639DA0E74ECF01763'  # PS2EXE @ MScholtes/PS2EXE d32d5ce
$tmpSrc    = Join-Path $PSScriptRoot '_build_tmp.ps1'

# ps2exe вендорится в репозитории (tools/ps2exe.ps1) и не качается на лету:
# pin на коммит d32d5ce + проверка SHA256 перед dot-source (supply-chain).
if (-not (Test-Path $ps2exePs)) {
    Write-Host "ERROR: vendored ps2exe not found: $ps2exePs"
    exit 1
}
$ps2exeActual = (Get-FileHash -Algorithm SHA256 $ps2exePs).Hash
if ($ps2exeActual -ne $ps2exeSha) {
    Write-Host "ERROR: ps2exe.ps1 SHA256 mismatch (expected $ps2exeSha, got $ps2exeActual)"
    exit 1
}

# --- Встраиваем script.ps1 в run_win.ps1 ---
Write-Host "Embedding FFmpeg_Converter_script.ps1..."
$scriptContent = [System.IO.File]::ReadAllText($scriptPs1, [System.Text.Encoding]::UTF8)

$embedBlock = @"

# === EMBEDDED SCRIPT (auto-generated by build_exe.ps1) ===
`$script:_embeddedScript = @'
$scriptContent
'@
# === END EMBEDDED SCRIPT ===
"@

$mainContent = [System.IO.File]::ReadAllText($src, [System.Text.Encoding]::UTF8)
# Вставляем встроенный скрипт ПЕРЕД первой строкой кода (после комментариев)
$combined = $embedBlock + "`n" + $mainContent
[System.IO.File]::WriteAllText($tmpSrc, $combined, [System.Text.Encoding]::UTF8)
Write-Host "Combined file: $([math]::Round((Get-Item $tmpSrc).Length / 1KB)) KB"

Write-Host "Loading ps2exe function..."
. $ps2exePs

# Удаляем прежний EXE ДО сборки: иначе при падении Invoke-ps2exe остался бы старый
# файл и Test-Path ниже дал бы ложный SUCCESS.
Remove-Item $out -Force -ErrorAction SilentlyContinue

Write-Host "Running Invoke-ps2exe..."
$ErrorActionPreference = 'Stop'
try {
    Invoke-ps2exe `
        -inputFile  $tmpSrc `
        -outputFile $out `
        -noConsole `
        -STA `
        -x64 `
        -title   "Video Converter (ffmpeg) v14" `
        -version "14.0.0.0"
} catch {
    Write-Host "FAIL: $_"
    Remove-Item $tmpSrc -Force -ErrorAction SilentlyContinue
    exit 1
}

Remove-Item $tmpSrc -Force -ErrorAction SilentlyContinue

if (Test-Path $out) {
    $size = [math]::Round((Get-Item $out).Length / 1KB)
    Write-Host "SUCCESS: $out ($size KB)"
} else {
    Write-Host "FAILED: EXE not created"
    exit 1
}
