$src       = 'S:\Private2\_task\LLM\_VSC\video\ffmpeg\FFmpeg_Converter_run_win_v12.ps1'
$scriptPs1 = 'S:\Private2\_task\LLM\_VSC\video\ffmpeg\FFmpeg_Converter_script.ps1'
$out       = 'S:\Private2\_task\LLM\_VSC\video\ffmpeg\_VideoConverter_v12.exe'
$ps2exePs  = 'S:\Private2\_task\LLM\_VSC\video\ffmpeg\ps2exe_tool.ps1'
$tmpSrc    = 'S:\Private2\_task\LLM\_VSC\video\ffmpeg\_build_tmp.ps1'

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

if (-not (Test-Path $ps2exePs)) {
    Write-Host "Downloading ps2exe..."
    try {
        Invoke-WebRequest `
            -Uri     'https://raw.githubusercontent.com/MScholtes/PS2EXE/master/Module/ps2exe.ps1' `
            -OutFile $ps2exePs `
            -Proxy   $env:HTTPS_PROXY
    } catch {
        Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/MScholtes/PS2EXE/master/Module/ps2exe.ps1' -OutFile $ps2exePs
    }
    Write-Host "Downloaded: $((Get-Item $ps2exePs).Length) bytes"
}

# --- Встраиваем script.ps1 в run_win.ps1 ---
Write-Host "Embedding FFmpeg_Converter_script.ps1..."
$scriptContent = [System.IO.File]::ReadAllText($scriptPs1, [System.Text.Encoding]::UTF8)
# Экранируем для heredoc: заменяем одинарные кавычки
$scriptEscaped = $scriptContent -replace "'", "''"

$embedBlock = @"

# === EMBEDDED SCRIPT (auto-generated by build_exe.ps1) ===
`$script:_embeddedScript = @'
$scriptContent
'@
# === END EMBEDDED SCRIPT ===
"@

$mainContent = [System.IO.File]::ReadAllText($src, [System.Text.Encoding]::UTF8)
# Вставляем встроенный скрипт ПЕРЕД первой строкой кода (после комментариев)
$combined = $embedBlock + "`n" + $mainContent
[System.IO.File]::WriteAllText($tmpSrc, $combined, [System.Text.Encoding]::UTF8)
Write-Host "Combined file: $([math]::Round((Get-Item $tmpSrc).Length / 1KB)) KB"

Write-Host "Loading ps2exe function..."
. $ps2exePs

Write-Host "Running Invoke-ps2exe..."
Invoke-ps2exe `
    -inputFile  $tmpSrc `
    -outputFile $out `
    -noConsole `
    -STA `
    -x64 `
    -title   "Video Converter (ffmpeg) v12" `
    -version "12.0.0.0"

Remove-Item $tmpSrc -Force -ErrorAction SilentlyContinue

if (Test-Path $out) {
    $size = [math]::Round((Get-Item $out).Length / 1KB)
    Write-Host "SUCCESS: $out ($size KB)"
    Remove-Item $ps2exePs -Force -ErrorAction SilentlyContinue
} else {
    Write-Host "FAILED: EXE not created"
    exit 1
}
