$src       = Join-Path $PSScriptRoot 'FFmpeg_Converter_run_win_v15.ps1'
$scriptPs1 = Join-Path $PSScriptRoot 'FFmpeg_Converter_script.ps1'
$out       = Join-Path $PSScriptRoot '_VideoConverter_v15.exe'
$ps2exePs  = Join-Path $PSScriptRoot '..\tools\ps2exe.ps1'
$tmpSrc    = Join-Path $PSScriptRoot '_build_tmp.ps1'

# Общие константы (SHA-пин ps2exe + версия) и проверка — один источник на оба build-скрипта.
. (Join-Path $PSScriptRoot '../tools/_build_common.ps1')
Assert-Ps2Exe $ps2exePs

# --- Встраиваем script.ps1 в run_win.ps1 ---
Write-Host "Embedding FFmpeg_Converter_script.ps1..."
$scriptContent = [System.IO.File]::ReadAllText($scriptPs1, [System.Text.Encoding]::UTF8)

$embedBlock = @"

# === EMBEDDED SCRIPT (auto-generated by build_exe.ps1) ===
`$script:_embeddedScript = @'
$scriptContent
'@
# === END EMBEDDED SCRIPT ===
"@

$mainContent = [System.IO.File]::ReadAllText($src, [System.Text.Encoding]::UTF8)
# Вставляем встроенный скрипт ПЕРЕД первой строкой кода (после комментариев)
$combined = $embedBlock + "`n" + $mainContent
[System.IO.File]::WriteAllText($tmpSrc, $combined, [System.Text.Encoding]::UTF8)
Write-Host "Combined file: $([math]::Round((Get-Item $tmpSrc).Length / 1KB)) KB"

Write-Host "Loading ps2exe function..."
. $ps2exePs

# Удаляем прежний EXE ДО сборки: иначе при падении Invoke-ps2exe остался бы старый
# файл и Test-Path ниже дал бы ложный SUCCESS.
Remove-Item $out -Force -ErrorAction SilentlyContinue

Write-Host "Running Invoke-ps2exe..."
$ErrorActionPreference = 'Stop'
try {
    Invoke-ps2exe `
        -inputFile  $tmpSrc `
        -outputFile $out `
        -noConsole `
        -STA `
        -x64 `
        -title   "Video Converter (ffmpeg) v15" `
        -version $script:BuildVersion
} catch {
    Write-Host "FAIL: $_"
    Remove-Item $tmpSrc -Force -ErrorAction SilentlyContinue
    exit 1
}

Remove-Item $tmpSrc -Force -ErrorAction SilentlyContinue

if (Test-Path $out) {
    $size = [math]::Round((Get-Item $out).Length / 1KB)
    Write-Host "SUCCESS: $out ($size KB)"
    Write-ExeChecksum $out
} else {
    Write-Host "FAILED: EXE not created"
    exit 1
}
